import { StyleSheet, Platform } from "react-native";
import { theme, fonts } from "../../theme";

export const styles = StyleSheet.create({
  // ─── Shell ───────────────────────────────────────────────────────────────
  shell: {
    flex: 1,
    backgroundColor: theme.bg,
    ...Platform.select({
      web: {
        height: "100%",
        minHeight: 0,
        overflow: "hidden",
      } as any,
    }),
  },
  scrollView: {
    flex: 1,
    ...Platform.select({
      web: {
        height: "100%",
      } as any,
    }),
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 220, // Space for floating nav and safe area
  },

  // ─── Top Bar ─────────────────────────────────────────────────────────────
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 20,
  },
  backButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  topBarCenter: {
    flex: 1,
    alignItems: "center",
  },
  topBarTitle: {
    color: theme.text,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -0.8,
  },
  topBarPhase: {
    color: theme.primary,
    fontSize: 10,
    ...fonts.bold,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginTop: 2,
  },
  alertBadge: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(186, 26, 26, 0.08)",
  },

  // ─── Progress bar ─────────────────────────────────────────────────────────
  progressWrap: {
    paddingHorizontal: 24,
    marginBottom: 24,
    gap: 10,
  },
  progressTrack: {
    height: 6,
    backgroundColor: "rgba(0,0,0,0.05)",
    borderRadius: 99,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: theme.danger,
    borderRadius: 99,
  },
  progressLabel: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },

  // ─── Decision Card ─────────────────────────────────────────────────────────
  decisionCard: {
    marginHorizontal: 24,
    borderRadius: 40,
    backgroundColor: theme.surface,
    padding: 32,
    gap: 28,
    borderWidth: 1.5,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 15 },
    elevation: 8,
  },
  decisionIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 15,
  },
  decisionLabel: {
    fontSize: 12,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  decisionTitle: {
    fontSize: 34,
    ...fonts.black,
    letterSpacing: -1.5,
    lineHeight: 40,
    color: theme.text,
  },
  decisionCopy: {
    fontSize: 16,
    lineHeight: 26,
    color: theme.textMuted,
    ...fonts.medium,
  },
  decisionOptions: {
    gap: 16,
  },
  optionButtonYes: {
    minHeight: 68,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 24,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
  },
  optionButtonNo: {
    minHeight: 68,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 24,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  optionButtonText: {
    fontSize: 18,
    ...fonts.black,
    color: "#fff",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  optionButtonTextDark: {
    fontSize: 18,
    ...fonts.black,
    color: theme.text,
    letterSpacing: 1,
    textTransform: "uppercase",
  },

  // ─── Step Card ─────────────────────────────────────────────────────────────
  stepCard: {
    marginHorizontal: 24,
    borderRadius: 40,
    backgroundColor: theme.surface,
    padding: 32,
    gap: 24,
    borderWidth: 1.5,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  stepIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  stepTag: {
    fontSize: 12,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  stepTitle: {
    fontSize: 32,
    ...fonts.black,
    letterSpacing: -1.2,
    lineHeight: 38,
    color: theme.text,
  },
  stepCopy: {
    fontSize: 16,
    lineHeight: 26,
    color: theme.textMuted,
    ...fonts.medium,
  },

  // ─── Info rows inside step cards ───────────────────────────────────────────
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: theme.surfaceAlt,
    padding: 18,
    borderRadius: 20,
    borderLeftWidth: 6,
  },
  infoRowText: {
    flex: 1,
    fontSize: 16,
    ...fonts.bold,
    color: theme.text,
    lineHeight: 24,
  },
  infoRowSub: {
    fontSize: 13,
    color: theme.textMuted,
    marginTop: 2,
    ...fonts.medium,
  },

  // ─── Upload box ─────────────────────────────────────────────────────────────
  uploadBox: {
    minHeight: 180,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: theme.lineMedium,
    borderStyle: "dashed",
    backgroundColor: "rgba(46, 125, 50, 0.05)",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  uploadBoxTitle: {
    fontSize: 18,
    ...fonts.black,
    color: theme.primary,
  },
  uploadBoxHint: {
    fontSize: 13,
    color: theme.textLight,
    textAlign: "center",
    lineHeight: 20,
    ...fonts.medium,
  },

  // ─── SMS code display ───────────────────────────────────────────────────────
  smsCodeBox: {
    backgroundColor: theme.text,
    borderRadius: 28,
    padding: 32,
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  smsCodeLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    ...fonts.bold,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  smsCode: {
    color: "#fff",
    fontSize: 48,
    ...fonts.black,
    letterSpacing: 10,
  },
  smsCodeHint: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
    marginTop: 8,
    ...fonts.medium,
  },

  // ─── QR display ────────────────────────────────────────────────────────────
  qrWrap: {
    alignItems: "center",
    gap: 20,
    paddingVertical: 12,
  },
  qrFrame: {
    width: 220,
    height: 220,
    borderRadius: 40,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 15 },
    elevation: 10,
  },
  qrImage: {
    width: 180,
    height: 180,
    borderRadius: 20,
  },
  qrIdBadge: {
    backgroundColor: theme.primarySoft,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 99,
  },
  qrIdText: {
    color: theme.primary,
    fontSize: 16,
    ...fonts.black,
    letterSpacing: 3,
  },

  // ─── Success / Confirm ─────────────────────────────────────────────────────
  confirmHero: {
    alignItems: "center",
    gap: 20,
    paddingVertical: 12,
  },
  confirmIconRing: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  confirmTitle: {
    fontSize: 32,
    ...fonts.black,
    color: theme.text,
    textAlign: "center",
    letterSpacing: -1,
  },
  confirmCopy: {
    fontSize: 16,
    color: theme.textMuted,
    textAlign: "center",
    lineHeight: 26,
    ...fonts.medium,
  },

  // ─── CTA Button ────────────────────────────────────────────────────────────
  ctaButton: {
    minHeight: 68,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 24,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  ctaButtonText: {
    fontSize: 18,
    ...fonts.black,
    color: "#fff",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  ghostButton: {
    minHeight: 60,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  ghostButtonText: {
    fontSize: 16,
    ...fonts.bold,
    color: theme.textLight,
  },

  // ─── Map mock ──────────────────────────────────────────────────────────────
  mapMock: {
    height: 220,
    borderRadius: 32,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  mapPin: {
    position: "absolute",
    top: "35%",
    left: "42%",
    alignItems: "center",
  },
  mapEtaBadge: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  mapEtaText: {
    fontSize: 14,
    ...fonts.bold,
    color: theme.primary,
  },

  // ─── Radar (existing) ──────────────────────────────────────────────────────
  radarRing: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.danger,
    position: "absolute",
  },
  coreDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: theme.danger,
    borderWidth: 2,
    borderColor: "#fff",
  },
});
