import { StyleSheet, Platform } from "react-native";
import { theme, fonts } from "../../../theme";

export const styles = StyleSheet.create({
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 20,
  },
  topBarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  topButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.line,
  },
  topBarTitle: {
    color: theme.text,
    fontSize: 24,
    ...fonts.black,
    letterSpacing: -1,
  },
  avatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: theme.primary,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  heroSection: {
    alignItems: "center",
    gap: 20,
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  successBadge: {
    width: 80,
    height: 80,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primarySoft,
  },
  heroTitle: {
    color: theme.text,
    fontSize: 42,
    lineHeight: 48,
    ...fonts.black,
    textAlign: "center",
    letterSpacing: -2,
  },
  heroCopy: {
    color: theme.textMuted,
    fontSize: 16,
    lineHeight: 26,
    textAlign: "center",
    ...fonts.medium,
  },
  cardShell: {
    marginHorizontal: 24,
    marginBottom: 40,
  },
  idCard: {
    backgroundColor: "#ffffff",
    borderRadius: 40,
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 15 },
    elevation: 10,
  },
  idHeader: {
    backgroundColor: theme.primary,
    paddingHorizontal: 32,
    paddingVertical: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  idHeaderLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 10,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  idHeaderTitle: {
    color: "#ffffff",
    fontSize: 20,
    ...fonts.black,
    marginTop: 4,
  },
  idHeaderMark: {
    color: "rgba(255,255,255,0.15)",
    fontSize: 40,
    ...fonts.black,
  },
  idContent: {
    padding: 32,
    gap: 32,
  },
  qrSection: {
    alignItems: "center",
    gap: 20,
  },
  qrFrame: {
    padding: 16,
    borderRadius: 32,
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 15,
  },
  qrImage: {
    width: 200,
    height: 200,
  },
  idCodeBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 99,
    backgroundColor: theme.primarySoft,
  },
  idCodeText: {
    color: theme.primary,
    fontSize: 16,
    ...fonts.black,
    letterSpacing: 3,
  },
  detailsSection: {
    gap: 24,
  },
  detailBlock: {
    gap: 8,
  },
  detailLabel: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  detailValue: {
    color: theme.text,
    fontSize: 32,
    lineHeight: 38,
    ...fonts.black,
    letterSpacing: -1,
  },
  detailGrid: {
    flexDirection: "row",
    gap: 20,
  },
  detailMiniBlock: {
    flex: 1,
    gap: 8,
  },
  verifiedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  verifiedText: {
    color: theme.primary,
    fontSize: 15,
    ...fonts.bold,
  },
  detailSmallValue: {
    color: theme.text,
    fontSize: 16,
    ...fonts.black,
  },
  regionBlock: {
    paddingTop: 24,
    borderTopWidth: 1.5,
    borderTopColor: theme.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  regionIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: theme.secondarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  regionText: {
    color: theme.text,
    fontSize: 15,
    ...fonts.bold,
  },
  actionsSection: {
    paddingHorizontal: 24,
    paddingBottom: 60,
    gap: 20,
  },
  toggleCard: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 28,
    padding: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: theme.line,
  },
  toggleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  toggleIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: theme.secondarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleTitle: {
    color: theme.text,
    fontSize: 17,
    ...fonts.black,
  },
  toggleCopy: {
    color: theme.textLight,
    fontSize: 13,
    marginTop: 2,
    ...fonts.medium,
  },
  primaryAction: {
    height: 68,
    borderRadius: 24,
    backgroundColor: theme.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  primaryActionText: {
    color: "#ffffff",
    fontSize: 18,
    ...fonts.black,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
});
