import { StyleSheet, Platform } from "react-native";
import { theme, fonts } from "../../../theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  content: {
    padding: 24,
    paddingBottom: 160,
    gap: 32,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  topBarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  iconButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.line,
  },
  topTitle: {
    color: theme.text,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  brand: {
    color: theme.primary,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -1,
  },
  heroSection: {
    gap: 16,
  },
  stepBadge: {
    alignSelf: "flex-start",
    backgroundColor: theme.secondarySoft,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  stepBadgeText: {
    color: theme.secondaryDark,
    fontSize: 10,
    ...fonts.black,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: theme.text,
    fontSize: 42,
    lineHeight: 48,
    ...fonts.black,
    letterSpacing: -2,
  },
  heroAccent: {
    color: theme.primary,
  },
  heroCopy: {
    color: theme.textMuted,
    fontSize: 16,
    lineHeight: 26,
    ...fonts.medium,
  },
  memberCard: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 32,
    padding: 28,
    gap: 24,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  memberHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  memberLabel: {
    color: theme.primary,
    fontSize: 11,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  memberTitle: {
    color: theme.text,
    fontSize: 22,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  memberStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  memberStatus: {
    color: theme.primary,
    fontSize: 13,
    ...fonts.bold,
  },
  memberGrid: {
    gap: 20,
  },
  fieldWrap: {
    gap: 10,
  },
  fieldLabel: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    paddingHorizontal: 4,
  },
  staticField: {
    minHeight: 64,
    borderRadius: 20,
    backgroundColor: theme.surface,
    borderWidth: 1.5,
    borderColor: theme.line,
    paddingHorizontal: 20,
    justifyContent: "center",
  },
  staticFieldText: {
    color: theme.text,
    fontSize: 17,
    ...fonts.bold,
  },
  newMemberCard: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 32,
    padding: 28,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: theme.lineMedium,
    gap: 28,
  },
  newMemberHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  memberNumber: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  memberNumberText: {
    color: "#ffffff",
    fontSize: 18,
    ...fonts.black,
  },
  newMemberLabel: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  newMemberTitle: {
    color: theme.text,
    fontSize: 22,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  formGrid: {
    gap: 24,
  },
  inputField: {
    minHeight: 64,
    backgroundColor: theme.surface,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: theme.line,
    paddingHorizontal: 20,
    color: theme.text,
    fontSize: 17,
    ...fonts.medium,
  },
  relationshipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingTop: 4,
  },
  relationshipChip: {
    backgroundColor: theme.surface,
    borderWidth: 1.5,
    borderColor: theme.line,
    borderRadius: 99,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  relationshipChipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  relationshipChipText: {
    color: theme.textLight,
    fontSize: 14,
    ...fonts.bold,
  },
  relationshipChipTextActive: {
    color: "#ffffff",
  },
  quickSelectSection: {
    gap: 16,
  },
  quickSelectRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  needChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1.5,
    borderColor: theme.line,
    borderRadius: 99,
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: theme.surface,
  },
  needChipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  needChipText: {
    color: theme.text,
    fontSize: 14,
    ...fonts.bold,
  },
  needChipTextActive: {
    color: "#ffffff",
  },
  actionRow: {
    gap: 16,
    paddingTop: 12,
  },
  secondaryButton: {
    height: 64,
    borderRadius: 24,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 12,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  secondaryButtonText: {
    color: theme.text,
    fontSize: 16,
    ...fonts.black,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  primaryButton: {
    height: 68,
    borderRadius: 24,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 12,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 18,
    ...fonts.black,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  sidebarCard: {
    backgroundColor: theme.primarySoft,
    borderRadius: 32,
    padding: 28,
    borderWidth: 1.5,
    borderColor: "rgba(46, 125, 50, 0.1)",
    gap: 12,
  },
  sidebarTitle: {
    color: theme.primary,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  sidebarCopy: {
    color: theme.textMuted,
    fontSize: 14,
    lineHeight: 22,
    ...fonts.medium,
  },
  privacyCard: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 32,
    padding: 28,
    gap: 16,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  privacyHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  privacyTitle: {
    color: theme.text,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  privacyCopy: {
    color: theme.textLight,
    fontSize: 13,
    lineHeight: 22,
    ...fonts.medium,
  },
});
