import { StyleSheet, Platform } from "react-native";
import { theme, fonts } from "../../../theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  content: {
    padding: 24,
    paddingBottom: 80,
    gap: 32,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 52,
    gap: 16,
  },
  topLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  iconButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.line,
  },
  topTitle: {
    color: theme.text,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  brand: {
    color: theme.primary,
    fontSize: 20,
    ...fonts.black,
    letterSpacing: -1,
  },
  heroSection: {
    gap: 16,
  },
  stepBadgeWrap: {
    alignSelf: "flex-start",
    backgroundColor: theme.secondarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  stepLabel: {
    color: theme.secondaryDark,
    fontSize: 10,
    ...fonts.black,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: theme.text,
    fontSize: 42,
    lineHeight: 48,
    ...fonts.black,
    letterSpacing: -2,
  },
  heroCopy: {
    color: theme.textMuted,
    fontSize: 16,
    lineHeight: 26,
    ...fonts.medium,
  },
  formSection: {
    gap: 20,
  },
  fieldGroup: {
    gap: 10,
  },
  fieldLabel: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    paddingHorizontal: 4,
  },
  textField: {
    minHeight: 64,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: theme.line,
    paddingHorizontal: 20,
    color: theme.text,
    fontSize: 17,
    ...fonts.medium,
  },
  fieldWithIcon: {
    minHeight: 64,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: theme.line,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  fieldInputFlex: {
    flex: 1,
    color: theme.text,
    fontSize: 17,
    ...fonts.medium,
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingTop: 4,
  },
  optionChip: {
    backgroundColor: theme.surface,
    borderWidth: 1.5,
    borderColor: theme.line,
    borderRadius: 99,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  optionChipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  optionChipText: {
    color: theme.textLight,
    fontSize: 14,
    ...fonts.bold,
  },
  optionChipTextActive: {
    color: "#ffffff",
  },
  medicalCard: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 32,
    padding: 28,
    borderLeftWidth: 6,
    borderLeftColor: theme.primary,
    gap: 24,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  medicalHeader: {
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
  },
  medicalIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primarySoft,
  },
  medicalHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  medicalTitle: {
    color: theme.text,
    fontSize: 22,
    ...fonts.black,
    letterSpacing: -0.5,
  },
  medicalSubtitle: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 20,
    ...fonts.medium,
  },
  medicalGrid: {
    gap: 24,
  },
  bloodTypeSection: {
    gap: 12,
  },
  bloodGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  bloodButton: {
    minWidth: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1.5,
    borderColor: theme.line,
    borderRadius: 16,
  },
  bloodButtonActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  bloodButtonText: {
    color: theme.text,
    fontSize: 16,
    ...fonts.black,
  },
  bloodButtonTextActive: {
    color: "#ffffff",
  },
  conditionsSection: {
    gap: 12,
  },
  textArea: {
    minHeight: 140,
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 20,
    color: theme.text,
    fontSize: 16,
    lineHeight: 24,
    ...fonts.medium,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  consentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
    paddingHorizontal: 4,
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: theme.lineMedium,
    backgroundColor: theme.surface,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkboxActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  consentText: {
    flex: 1,
    color: theme.textMuted,
    fontSize: 14,
    lineHeight: 22,
    ...fonts.medium,
  },
  consentLink: {
    color: theme.primary,
    ...fonts.bold,
    textDecorationLine: "underline",
  },
  actionSection: {
    paddingTop: 12,
  },
  primaryButton: {
    height: 68,
    borderRadius: 24,
    backgroundColor: theme.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 18,
    ...fonts.black,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
});
