import { StyleSheet } from "react-native";
import { theme, fonts } from "../../theme";

export const styles = StyleSheet.create({
  citizenShell: {
    paddingHorizontal: 20,
    backgroundColor: theme.bg,
  },
  orb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.12,
  },
  orb1: {
    width: 300,
    height: 300,
    backgroundColor: theme.primary,
    top: -120,
    right: -120,
  },
  orb2: {
    width: 250,
    height: 250,
    backgroundColor: theme.secondary,
    top: 650,
    left: -100,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderRadius: 32,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.6)",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 6 },
    zIndex: 100,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primarySoft,
  },
  brandText: {
    color: theme.text,
    fontSize: 22,
    ...fonts.black,
    letterSpacing: -1,
  },
  roleBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  roleTag: {
    color: theme.textMuted,
    fontSize: 10,
    ...fonts.bold,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  avatarIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.line,
  },
  editorialPanel: {
    marginTop: 32,
    gap: 16,
  },
  gatewayLabel: {
    textTransform: "uppercase",
    letterSpacing: 3,
    ...fonts.bold,
    fontSize: 12,
    color: theme.primary,
  },
  editorialTitle: {
    color: theme.text,
    fontSize: 34,
    lineHeight: 38,
    ...fonts.black,
    letterSpacing: -1.5,
  },
  editorialAccent: {
    color: theme.primary,
  },
  editorialText: {
    color: theme.textMuted,
    fontSize: 16,
    lineHeight: 26,
    ...fonts.medium,
  },
  imageCardContainer: {
    marginTop: 8,
    borderRadius: 32,
    overflow: "hidden",
    backgroundColor: theme.surfaceAlt,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  imageCard: {
    height: 180,
    justifyContent: "flex-end",
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.03)",
  },
  imageFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 20,
    backgroundColor: "rgba(255,255,255,0.85)",
  },
  imageFooterText: {
    fontSize: 12,
    ...fonts.bold,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: theme.textLight,
  },
  loginCard: {
    marginTop: -50,
    backgroundColor: theme.surface,
    borderRadius: 40,
    padding: 28,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 15 },
    elevation: 12,
    borderWidth: 1,
    borderColor: theme.line,
  },
  loginTitle: {
    color: theme.text,
    fontSize: 34,
    ...fonts.black,
    marginBottom: 8,
    letterSpacing: -1.5,
  },
  loginSubtitle: {
    color: theme.textMuted,
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 32,
    ...fonts.medium,
  },
  fieldGroup: {
    marginBottom: 24,
  },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  fieldLabel: {
    color: theme.text,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 2,
    paddingHorizontal: 4,
  },
  helpLink: {
    fontSize: 11,
    ...fonts.bold,
    color: theme.primary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  fieldWrap: {
    height: 68,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.surfaceAlt,
    borderRadius: 24,
    paddingHorizontal: 20,
    borderWidth: 1.5,
    borderColor: theme.line,
  },
  fieldInput: {
    flex: 1,
    color: theme.text,
    fontSize: 17,
    ...fonts.semibold,
  },
  actionStack: {
    marginTop: 12,
    gap: 16,
  },
  primaryAction: {
    height: 68,
    borderRadius: 24,
    backgroundColor: theme.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  primaryActionText: {
    color: "#fff",
    fontSize: 16,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1.5,
    backgroundColor: theme.line,
  },
  dividerText: {
    paddingHorizontal: 16,
    color: theme.textLight,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  secondaryAction: {
    height: 64,
    borderRadius: 24,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
  },
  secondaryActionText: {
    fontSize: 14,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  tertiaryAction: {
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  tertiaryActionText: {
    color: theme.textLight,
    fontSize: 12,
    ...fonts.bold,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    opacity: 0.8,
  },
  footer: {
    marginTop: 40,
    paddingBottom: 40,
    gap: 16,
    alignItems: "center",
  },
  footerLinks: {
    flexDirection: "row",
    gap: 24,
  },
  footerLink: {
    fontSize: 12,
    ...fonts.black,
    color: theme.textLight,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  footerNote: {
    fontSize: 12,
    color: theme.textLight,
    lineHeight: 20,
    textAlign: "center",
    maxWidth: "80%",
    ...fonts.medium,
  },
});
