import { StyleSheet } from "react-native";
import { theme, fonts } from "../theme";

export const styles = StyleSheet.create({
  citizenShell: { paddingHorizontal: 24, backgroundColor: theme.bg },
  orb: { position: "absolute", borderRadius: 999, opacity: 0.08 },
  orb1: { width: 280, height: 280, top: -120, right: -100 },
  orb2: { width: 220, height: 220, bottom: 80, left: -90, backgroundColor: theme.secondary },
  topBar: { marginTop: 8, marginBottom: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  menuButton: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: theme.primarySoft },
  menuButtonText: { fontSize: 20, ...fonts.black, color: theme.text },
  brandText: { fontSize: 18, ...fonts.black, color: theme.text, letterSpacing: 1.1 },
  roleBadgeRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  roleTag: { fontSize: 11, ...fonts.bold, color: theme.textLight, textTransform: "uppercase", letterSpacing: 1.3 },
  avatarIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: theme.surfaceAlt },
  editorialPanel: { gap: 10, marginBottom: 18 },
  gatewayLabel: { fontSize: 11, ...fonts.bold, textTransform: "uppercase", letterSpacing: 1.5 },
  editorialTitle: { fontSize: 30, lineHeight: 34, ...fonts.black, color: theme.text },
  editorialAccent: { ...fonts.black },
  editorialText: { fontSize: 14, lineHeight: 22, color: theme.textMuted, ...fonts.medium },
  imageCard: { marginTop: 10, height: 170, borderRadius: 28, overflow: "hidden", justifyContent: "flex-end" },
  imageOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.15)" },
  imageFooter: { flexDirection: "row", alignItems: "center", gap: 8, padding: 12 },
  verifiedIcon: { fontSize: 16, ...fonts.black },
  imageFooterText: { fontSize: 12, ...fonts.medium },
  loginCard: { marginTop: 8, borderRadius: 26, borderWidth: 1, borderColor: theme.line, backgroundColor: theme.surface, overflow: "hidden" },
  glowOrb: { position: "absolute", top: -35, right: -45, width: 140, height: 140, borderRadius: 70, backgroundColor: theme.primarySoft },
  loginCardInner: { padding: 20, gap: 8 },
  loginIntro: { marginBottom: 12 },
  loginTitle: { fontSize: 30, ...fonts.black, color: theme.text, letterSpacing: -0.8 },
  loginSubtitle: { marginTop: 4, fontSize: 14, lineHeight: 21, color: theme.textMuted, ...fonts.medium },
  fieldGroup: { marginBottom: 12 },
  fieldLabel: { marginBottom: 6, fontSize: 12, ...fonts.bold, color: theme.textLight, textTransform: "uppercase", letterSpacing: 1.1 },
  fieldWrap: { height: 52, borderRadius: 14, borderWidth: 1, borderColor: theme.line, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: theme.surfaceAlt },
  fieldIcon: { fontSize: 12, color: theme.textLight },
  fieldInput: { flex: 1, fontSize: 14, ...fonts.medium, color: theme.text },
  labelRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  helpLink: { fontSize: 12, ...fonts.bold },
  visibilityToggle: { fontSize: 12, ...fonts.bold, color: theme.textLight },
  actionStack: { marginTop: 8, gap: 12 },
  primaryAction: { borderRadius: 14, overflow: "hidden" },
  primaryGradient: { height: 52, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  primaryActionText: { color: "#fff", fontSize: 13, ...fonts.black, textTransform: "uppercase", letterSpacing: 1.2 },
  primaryActionArrow: { color: "#fff", fontSize: 16, ...fonts.black },
  dividerRow: { flexDirection: "row", alignItems: "center", marginVertical: 4 },
  dividerLine: { flex: 1, height: 1, backgroundColor: theme.line },
  dividerText: { paddingHorizontal: 10, fontSize: 11, ...fonts.bold, color: theme.textLight, textTransform: "uppercase", letterSpacing: 1 },
  secondaryAction: { height: 48, borderRadius: 12, borderWidth: 1, borderColor: theme.line, alignItems: "center", justifyContent: "center", backgroundColor: theme.surfaceAlt },
  secondaryActionText: { fontSize: 12, ...fonts.black, color: theme.text, textTransform: "uppercase", letterSpacing: 1.1 },
  footer: { marginTop: 20, alignItems: "center", gap: 10, paddingBottom: 30 },
  footerLinks: { flexDirection: "row", gap: 16 },
  footerLink: { fontSize: 11, ...fonts.bold, color: theme.textLight },
  footerNote: { textAlign: "center", fontSize: 11, lineHeight: 17, color: theme.textLight, ...fonts.medium },
});
