import { StyleSheet } from "react-native";
import { theme, fonts } from "../theme";

export const styles = StyleSheet.create({
  hero: {
    paddingTop: 64,
    paddingBottom: 48,
    backgroundColor: theme.surface,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    marginBottom: 32,
    position: "relative",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  heroGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.primarySoft,
  },
  orb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.08,
  },
  orb1: {
    width: 200,
    height: 200,
    backgroundColor: theme.secondary,
    top: -50,
    right: -50,
  },
  orb2: {
    width: 150,
    height: 150,
    backgroundColor: theme.primary,
    bottom: -30,
    left: -20,
  },
  mark: {
    width: 56,
    height: 56,
    backgroundColor: theme.primary,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    shadowColor: theme.primary,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  markText: {
    color: "#fff",
    fontSize: 26,
    ...fonts.black,
  },
  brand: {
    color: theme.primary,
    fontSize: 12,
    ...fonts.bold,
    letterSpacing: 4,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  headline: {
    color: theme.text,
    fontSize: 38,
    lineHeight: 44,
    ...fonts.black,
    marginBottom: 16,
    letterSpacing: -1.5,
  },
  copy: {
    color: theme.textMuted,
    fontSize: 16,
    lineHeight: 24,
    maxWidth: "95%",
    marginBottom: 32,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.8)",
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statValue: {
    color: theme.text,
    fontSize: 16,
    ...fonts.bold,
  },
  statLabel: {
    color: theme.textLight,
    fontSize: 11,
    ...fonts.bold,
    textTransform: "uppercase",
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: theme.line,
  },
  selectorHeadText: {
    fontSize: 12,
    color: theme.textLight,
    ...fonts.bold,
    letterSpacing: 2,
    marginLeft: 24,
    marginBottom: 16,
    textTransform: "uppercase",
  },
  roleCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.surface,
    padding: 28,
    borderRadius: 40,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    position: "relative",
  },
  roleIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 20,
  },
  roleCopy: {
    flex: 1,
  },
  roleSub: {
    fontSize: 10,
    ...fonts.black,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 4,
  },
  roleLabel: {
    fontSize: 24,
    color: theme.text,
    ...fonts.black,
    marginBottom: 8,
    letterSpacing: -1,
  },
  roleDesc: {
    fontSize: 14,
    color: theme.textMuted,
    lineHeight: 22,
    ...fonts.medium,
  },
  roleActionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surfaceAlt,
    marginLeft: 12,
  },
  statusDot: {
    position: "absolute",
    top: 20,
    left: 20,
    width: 12,
    height: 12,
    borderRadius: 6,
    zIndex: 10,
  },
});
