import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#2e7d32",
        "inverse-surface": "#2f312e",
        "on-secondary-fixed": "#281900",
        "primary-fixed": "#a3f69c",
        "on-background": "#1a1c19",
        "on-tertiary-fixed-variant": "#07521d",
        "surface-dim": "#dadad5",
        "primary-fixed-dim": "#88d982",
        "surface-container": "#eeeee9",
        "surface-tint": "#1b6d24",
        "on-secondary-fixed-variant": "#604100",
        "surface-variant": "#e2e3de",
        "secondary-container": "#feb300",
        "tertiary": "#1d622b",
        "tertiary-fixed": "#abf4ac",
        "surface": "#fafaf5",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#002107",
        "outline-variant": "#bfcaba",
        "outline": "#707a6c",
        "on-primary-fixed": "#002204",
        "tertiary-container": "#387b41",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#90d792",
        "on-surface": "#1a1c19",
        "surface-container-low": "#f4f4ef",
        "surface-container-high": "#e8e8e4",
        "surface-container-highest": "#e2e3de",
        "on-tertiary-container": "#c7ffc5",
        "background": "#fafaf5",
        "on-secondary-container": "#6a4800",
        "error-container": "#ffdad6",
        "surface-bright": "#fafaf5",
        "on-primary": "#ffffff",
        "primary": "#0d631b",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#005312",
        "inverse-primary": "#88d982",
        "secondary-fixed": "#ffdeac",
        "secondary": "#7e5700",
        "inverse-on-surface": "#f1f1ec",
        "secondary-fixed-dim": "#ffba38",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#40493d",
        "on-error": "#ffffff",
        "on-primary-container": "#cbffc2"
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
